[package]
name = "basic_ml"
version = "0.1.0"
authors = ["Rob <rm.rf.etc@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
